ESP8266 Support
michaelkamprath/rgb-led-matrix pull request #5
Opened 2017-10-12 13:52 UTC by peternlewis

Added support for NodeMCU/ESP8266.

2017-10-12 16:00 UTC, michaelkamprath requested changes

2017-10-12 16:00 UTC, michaelkamprath commented on drivers/arduino/RGB_LED_Matrix_Lib/src/RGBLEDMatrix.cpp
> +	timer0_detachInterrupt;
Shouldn't this be a function call? That is:
```
	timer0_detachInterrupt();
```
Note the addition of the parenthesis.

2017-10-12 23:58 UTC, peternlewis commented
On 13 Oct 2017, at 00:00, Michael Kamprath <notifications@github.com> wrote:
> Shouldn't this be a function call? That is:
> 
> 	timer0_detachInterrupt();
> 
> Note the addition of the parenthesis.

Yes.

I expect it never happens, when would stopScanning() ever be called?

Thanks,
   Peter.

-- 
Keyboard Maestro <https://www.keyboardmaestro.com/> Editors' Choice Award winner.
Macros for your Mac <https://download.keyboardmaestro.com/>
Join us on the Keyboard Maestro forum <https://forum.keyboardmaestro.com/>

2017-10-13 00:18 UTC, michaelkamprath commented
@peternlewis I would call `stopScanning(void)` if I need to suspend the use of the interrupt or even updating of the screen for whatever reason. Admittedly, looking at this, I see the original code had a bug in that the `stopScanning(void)` method needs to be scoped to the `RGBLEDMatrix`. Obvious I don't use it much myself :-/ 

I will merge and fix it myself when I fix my own bug.

2017-10-13 05:42 UTC, peternlewis commented
OK, I'll leave it to you.

2017-10-13 07:58 UTC, michaelkamprath approved these changes

2017-10-13 07:58 UTC, merged